### ISSUE TITLE
binstubs stupport

### ISSUE THREAD

**Issue by jyurek** [postmodern/chruby#117]
Using chruby masks binstubs installed per-project (http://robots.thoughtbot.com/post/15346721484/use-bundlers-binstubs). I see in the contribution guidelines that you want to cut down on environment variable proliferation, which I agree with, but allowing a sub-path that gets prepended to the modified PATH each time ruby is changed seems most appropriate for this problem. I'd like to submit a pull request for this, but I'm not sure this approach would be accepted. Any advice?

**Comment by franklinyu** [comment]
It's interesting that `rails` now respect binstubs (tried with Rails 5.0.0.1). It might be slightly less dangerous to allow only a whitelist in `./bin` (such as `rails`, `rake` and `puma`) so that important binaries like `less` and `cat` won't be overrided.
