### ISSUE TITLE
Building a .deb for chruby

### ISSUE THREAD

**Issue by tpitale** [postmodern/chruby#135]
I started working on building a .deb file for ubuntu/debian systems and wanted to continue the conversation here (rather than on twitter :-).

Here's what I did so far and it "works". https://gist.github.com/tpitale/5500002

This is not really repeatable for the project, and it sounds like @postmodern had some other changes he wanted me to make.

**Comment by mcandre** [comment]
+1 a Debian package and Ubuntu PPA would be much appreciated!

**Comment by franklinyu** [comment]
The current update workflow is to `make uninstall` before re-installation. Having a Debian package greatly eases update of this tool. Jobs like bumping versions can be done by a server regularly checking tags on GitHub.
