### ISSUE TITLE
Error when no rubies are found

### ISSUE THREAD

**Issue by andrew-d** [postmodern/chruby#161]
Hey there,

When a directory is present in the RUBIES variable, but is empty, I get this error:

```
/usr/local/opt/chruby/share/chruby/chruby.sh:4: no matches found: /opt/rubies/*
```

I'm not great at Bash, so I'm hesitant to suggest a fix, but I'd like to request that it doesn't error if the directory is present but empty.

Thanks for the great tool!

**Comment by ELLIOTTCABLE** [comment]
Unfortunately, this fix depends on `ls` being unaliased, and breaks if the user has additional flags aliased onto `ls` by default.

Easiest fix is to surround calls out to system utilities (as opposed to builtins) with single-quotes, something like:

```diff
 for dir in "$PREFIX/opt/rubies" "$HOME/.rubies"; do
-	[[ -d "$dir" && -n "$(ls -A "$dir")" ]] && RUBIES+=("$dir"/*)
+	[[ -d "$dir" && -n "$('ls' -A "$dir")" ]] && RUBIES+=("$dir"/*)
 done
 unset dir
```

**Comment by philipbjorge** [comment]
WRT @ELLIOTTCABLE's comment, this manifested as `chruby: /Users/philipbjorge/.rubies/ruby-2.5.1/bin/ruby not executable` for me
