### ISSUE TITLE
Ruby switches to system when pianobar loses internet connection

### ISSUE THREAD

**Issue by jc00ke** [postmodern/chruby#170]
I :poop: you not, I don't really even know where to start. I swear, I'm not trolling you.

I have chruby set to `2.0.0` in my `.bashrc` and everything is good. I was listening to [pianobar](/PromyLOPh/pianobar) and my internet connection dropped, causing `pianobar` to stop playing. I hit `Ctrl c` to quit `pianobar` and then chruby defaulted to my system Ruby.

![selection_001](https://f.cloud.github.com/assets/18191/740560/d1ec6b3e-e37a-11e2-9932-44d510fdc339.png)

I'm running chruby `0.3.6` on Ubuntu 13.04 from within `tmux`

Let me know how I can help figure this out. Kinda looks like the `ENV` var gets blown away, since it no longer shows up in my [prompt](/jc00ke/bin/blob/e96dbb4424d95be85b6e694e5d5bec8887c4b0e9/ps1_functions#L88-L91).

**Comment by matthutchinson** [comment]
I got around this by modifying copying auto.sh and sourcing this modified version; which has this:

```
if [[ -n "$RUBY_AUTO_VERSION" ]]; then
  if [[ -n "~/.ruby-version" ]]; then
    chruby `cat ~/.ruby-version`
  else
    chruby_reset
    unset RUBY_AUTO_VERSION
  fi
fi
```

Instead of:

```
if [[ -n "$RUBY_AUTO_VERSION" ]]; then
  chruby_reset
  unset RUBY_AUTO_VERSION
fi
```
