### ISSUE TITLE
Sublime Text doesn't use chruby

### ISSUE THREAD

**Issue by michaelrkn** [postmodern/chruby#194]
[Sorry if this is the wrong place - couldn't figure out where else to go.]

I can't for the life of me figure out how to make Sublime Text use chruby. If would be awesome to have it added to the Integration section of the wiki.

I found [instructions for RVM](http://rubenlaguna.com/wp/2012/12/07/sublime-text-2-rvm-rspec-take-2/) but can't quite figure how to adapt them for chruby. 

Thanks! And thanks for such a lovely ruby-switcher.

**Comment by bkroeker** [comment]
I think I was able to solve this issue in Sublime Text 3.

Settings > Package Settings > RuboCop > Settings - User

I added the two scripts which chruby got me to add in my .zshrc: 
```
{
  "check_for_rvm": false,
  "rubocop_command": "source /usr/local/opt/chruby/share/chruby/chruby.sh; source /usr/local/opt/chruby/share/chruby/auto.sh; bundle exec rubocop"
}
```
