### ISSUE TITLE
Some Vagrant base boxes' links are broken

### ISSUE THREAD

**Issue by almog** [postmodern/chruby#197]
`https://dl.dropbox.com/u/1543052/Boxes/DebianSqueeze64.box` - 404
`http://dl.dropbox.com/u/1537815/precise64.box` 509 too much traffic
`https://github.com/downloads/xironix/freebsd-vagrant/freebsd_amd64_ufs.box` - 404

**Comment by postmodern** [comment]
Closing this since I started using `schroot` and `debootstrap`. Haven't used the BSD Vagrant images in a long time.
