### ISSUE TITLE
Chruby Doesn't Support Binstubs

### ISSUE THREAD

**Issue by joseph-ravenwolfe** [postmodern/chruby#202]
Chruby's `auto.sh` does not add the `./bin` to `$PATH` when a `.ruby-version` file is encountered.

It appears the Rails team and Rbenv contributor prescribe that it is the responsibility of  a ruby version manager to provide this functionality so that binstubs may be used as expected.

**Comment by franklinyu** [comment]
Possible duplicate of #117.
