### ISSUE TITLE
instructions for uninstall?

### ISSUE THREAD

**Issue by jrochkind** [postmodern/chruby#208]
Would it be possible to have documentation include instructions for complete uninstall?

I think it's probably pretty straightforward, but the installation process isn't neccesarily super explicit about what it's doing or where it's putting things. 

Although an uninstall script (`chruby uninstall`?) probably wouldn't hurt either, in case exactly what has to be removed changes in future versions, so you don't need to document different processes for different versions, people can just run the uninstall script and know it'll do the right thing for the version installed.

**Comment by Ammet** [comment]
After typing `sudo make uninstall` 
```
-bash: /usr/local/share/chruby/chruby.sh: No such file or directory
-bash: /usr/local/share/chruby/auto.sh: No such file or directory
```
Appears every time I open a terminal or run OS. How can I clean all bounded with chruby?

**Comment by havenwood** [comment]
@Ammet Remove the `source /usr/local/share/chruby/chruby.sh` and `source /usr/local/share/chruby/auto.sh` lines from your `~/.bashrc` file.

**Comment by Ammet** [comment]
@havenwood I have no such lines in my `~/.bashrc`

**Comment by havenwood** [comment]
@Ammet Might you have put the source lines in one of your other dotfiles like `~/.profile`, `~/.bash_login` or `~/.bash_profile`?

**Comment by Ammet** [comment]
All this files are not contain this . =(

**Comment by chrisnicola** [comment]
Ran into this issue. chruby puts a file in /etc/profile.d/chruby.sh that needs to be deleted. Probably should be something `make uninstall` does.

**Comment by postmodern** [comment]
@chrisnicola only the `setup.sh` installs any configuration. Should `make uninstall` really delete the configuration? Or perhaps we could add a `[[ -d $PREFIX/share/chruby ]]` check to prevent loading the files once they've been uninstalled.

**Comment by hugebag** [comment]
> 
> 
> Ran into this issue. chruby puts a file in /etc/profile.d/chruby.sh that needs to be deleted. Probably should be something `make uninstall` does.

FWIW, the script is named /etc/profile.d/use-app-ruby.sh on my machine. It needs to be renamed/removed to stop chruby from changing the PATH (which messes up what rvm does).

**Comment by postmodern** [comment]
I added `scripts/uninstall` (d98435ae8168f1989052de8c7f9f4c14413a88ad) which removes `/etc/profile.d/chruby.sh` created by `scripts/setup.sh`. I also made the default chruby config check if chruby is still installed before sourcing it's files (711c710fb829f0169a1aee7df0b5057f3f1fe1ba). In the future, if you installed chruby via `scripts/setup.sh` run `scripts/uninstall.sh` to fully uninstall.
