### ISSUE TITLE
chruby doesn't install properly via Homebrew using Mavericks*

### ISSUE THREAD

**Issue by Integralist** [postmodern/chruby#221]
*and to be clear I did a fresh install on my home laptop and installed chruby no problem.

The issue I'm having is on my work laptop which was previously running Mountain Lion and I installed Mavericks over the top.

Consider I'm in the root directory `cd ~/`.

I've uninstalled chruby `brew uninstall chruby` and installed it again `brew install chruby`. But whenever I run the command `chruby` or `chruby --version` I just get the stdout: 

``` sh
chruby_auto:9: command not found: chruby
/usr/local/opt/chruby/share/chruby/chruby.sh:5: no matches found: /opt/rubies/*
```

...the second line is kind of unstandable as I don't have any Ruby versions installed now (I manually deleted them all just before I uninstalled and re-installed chruby via Homebrew). 

The first line is the real indicator of my current problem. 

The fact that although I can run `brew list | grep chruby` and clearly see `chruby` returned and yet not have the command available to me to use.

Any ideas or suggestions?

I'm not sure if it helps but here are some other details that may or may not be useful in figuring out the problem...

**My `$PATH`...**

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**My default `gem env` settings are...**

``` sh
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.3
  - RUBY VERSION: 2.0.0 (2013-06-27 patchlevel 247) [universal.x86_64-darwin13]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-13
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/markmcdonnell/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
```

**Comment by globalkeith** [comment]
Had the same issue, the `.bash_profile` tricks described here worked a treat, thanks!!

**Comment by bbiglari** [comment]
Thanks Postmodern, It fix my issue !!!
