### ISSUE TITLE
/bin/bash -l or su -l runs profile chruby but GEM_HOME and GEM_PATH are empty

### ISSUE THREAD

**Issue by tpitale** [postmodern/chruby#236]
I've been trying to build a simple upstart config for a ruby script, but whenever it is run the GEM_HOME and GEM_PATH are empty.

Essentially, I've been trying to `su -l -c "echo $GEM_HOME" deploy`. I have /etc/profile.d/chruby.sh, and it is being run, and so is the sourced /usr/local/share/chruby/chruby.sh.

I'd be happy to provide any other information. Or maybe it's just obvious as to why this won't work.

**Comment by x-yuri** [comment]
Could it possibly be since the script is run [as root][1]?

[1]: https://github.com/postmodern/chruby/blob/master/share/chruby/chruby.sh#L54-58

**Comment by tpitale** [comment]
I think this is a very old issue, I have upstart working with chruby … sorry I lost track of this issue.
