### ISSUE TITLE
chruby sets RUBYOPT to ruby version

### ISSUE THREAD

**Issue by alisnic** [postmodern/chruby#239]
``` bash
/media/truecrypt1/salt-js/test/dummy master ✗  
❯ chruby ruby 2.0.0

/media/truecrypt1/salt-js/test/dummy master ✗  
❯ bundle exec teaspoon
ruby: invalid option -2  (-h will show valid options) (RuntimeError)

/media/truecrypt1/salt-js/test/dummy master ✗  
❯ env | grep RUBYOPT
RUBYOPT=2.0.0

/media/truecrypt1/salt-js/test/dummy master ✗  
❯ unset RUBYOPT  

/media/truecrypt1/salt-js/test/dummy master ✗  
❯ bundle exec teaspoon
Starting the Teaspoon server...
...
```

commenting https://github.com/postmodern/chruby/blob/master/share/chruby/chruby.sh#L42 fixes the problem

**Comment by strand** [comment]
Hey @alisnic, everybody feels like an idiot sometime. It's cool, don't worry about it.

I'm glad you filed this bug report, it helped me figure out where some of my companies internal documentation wasn't clear enough.

**Comment by sunnovations** [comment]
Ah, this bit me too, and I had no idea that this was happening. Perhaps add output to the chruby command when this takes place? :) "Chosen ruby 2.1.3 with arguments XYZ"

**Comment by postmodern** [comment]
@sunnovations that is a brilliant idea!
