### ISSUE TITLE
Can Rubymine be accomodated by Chruby?

### ISSUE THREAD

**Issue by timuckun** [postmodern/chruby#275]
Please see this discussion.

http://youtrack.jetbrains.com/issue/RUBY-14086#comment=27-761030

Thanks.

**Comment by fesplugas** [comment]
https://youtrack.jetbrains.com/issue/RUBY-14086#comment=27-1266480

**Comment by dctr** [comment]
I know this is old, but actually RM isn't ignoring the env, but running with the default one. If you run `chruby FOO && rubymine` everything works as expected.

**Comment by timuckun** [comment]
Can you run chruby without params so it can read the .ruby-version?

**Comment by dctr** [comment]
Of course, if you e.g. have the auto.sh in your shellrc, it will switch the version automatically. But you have to run RM from the terminal in order for it to pick up you current shell's environment.

You can always check your current environment through `gem env` or `chruby`.

**Comment by rkrdo** [comment]
It looks like support for chruby will finally get added 😃 

- https://youtrack.jetbrains.com/issue/RUBY-14086#tab=Comments&u=1416768003178
- https://www.jetbrains.com/ruby/nextversion/
