### ISSUE TITLE
SHELL env var assumes bash syntax

### ISSUE THREAD

**Issue by JoshCheek** [postmodern/chruby#284]
I use [fish](http://fishshell.com/), but never set my SHELL env var before. Recently had to do this to use [an editor plugin](https://github.com/webBoxio/atom-term2/blob/3a563d1300a7112b4c473b94cc2efab31130c90b/lib/TermView.coffee#L28).

But it breaks chruby [here](https://github.com/postmodern/chruby/blob/dadcdba85e50fd2b62930d6bb7835972873f879b/bin/chruby-exec#L36-39) because the `&&` is not valid fish syntax, fish uses the [`and`](http://fishshell.com/docs/current/commands.html#and) command.

-----

I played around with it a bit, trying things like this:

```sh
command="source /usr/local/opt/chruby/share/chruby/chruby.sh; chruby $argv && $SHELL $*"

if [[ -t 0 ]]; then exec "/bin/bash" -i -l -c "$command"
else                exec "/bin/bash"    -l -c "$command"
fi
```

But never actually got it working. In the end, I just overrode SHELL for the command that invokes chruby, but that wouldn't work if it needed to both invoke Ruby and start a shell.

**Comment by postmodern** [comment]
Since fish is not POSIX compliant, we can't really support it, let alone `dash` or `ksh`.
