### ISSUE TITLE
bundle install keeps looking for non-existent ruby

### ISSUE THREAD

**Issue by jrochkind** [postmodern/chruby#300]
I can't quite understand what's going on. I installed `ruby-2.0.0-p576`, and could switch to it with `chruby`, but `bundle install` kept trying to use `ruby-2.0.0-p247` instead. 

I deleted `ruby-2.0.0-p247` entirely, and for good measure deleted p576 too and re-installed it. Now p576 is the only ruby 2.0.0 I have.  But when I switch to it with chruby and try `bundle install` -- it still keeps trying to use `ruby-2.0.0-p247`, which does not exist, and complaining about it. I can't figure out what would even possibly be `remembering` p247. 

~~~bash
$ chruby 2.0.0-p576
$ ruby -v
ruby 2.0.0p576 (2014-09-19 revision 47628) [x86_64-darwin12.5.0]
$ bundle install
-bash: /Users/jrochkind/.gem/ruby/2.0.0/bin/bundle: /opt/rubies/ruby-2.0.0-p247/bin/ruby: bad interpreter: No such file or directory
$ ls /opt/rubies/
1.8.7-p374		rubinius-2.0.0-rc1	ruby-2.0.0-p576
jruby-1.6.8		ruby-1.9.3-p429		ruby-2.1.0
jruby-1.7.16		ruby-1.9.3-p448		ruby-2.1.3
jruby-1.7.6		ruby-1.9.3-p484
~~~

Any idea what's going on and what I do about it?  Thanks!

**Comment by postmodern** [comment]
Closing this. Adding `--env-shebang` to `~/.gemrc` is also a viable workaround until rubygems defaults to `#!/usr/bin/env`.
