### ISSUE TITLE
It would be nice to call chruby_auto without enabling auto-switching

### ISSUE THREAD

**Issue by DavidEGrayson** [postmodern/chruby#310]
Today I changed a project from using RVM to using chruby.  I had to replace the following line in a shell script:

```
rvm rvmrc load
```

with this line:

```
chruby $(cat ../.ruby-version)
```

The unpleasant thing about this is that I had to hardcode the path to the `.ruby-version` file, so the shell script will be more likely to break in the future, and if it gets copied to a different directory then that line would have to be modified.

Really what I would like to do is call some chruby function that searches up the directory tree for a `.ruby-version` file and then uses it.  That's what the `chruby_auto` function does.  I would suggest that the `chruby_auto` function should be moved from `auto.sh` to `chruby.sh` so it can be called without forcing the user to enable the auto-switching feature.

It would be even better if there were a function available in `chruby.sh` that was like `chruby_auto` but also emitted an error if it fails to find the `.ruby-version` file and switch rubies.

**Comment by pdg137** [comment]
I second David's suggestion.  There are lots of times you wouldn't want to load `auto.sh` but still want to do a one-time load of an environment specified by `.ruby-version`.  For example, on a production server, having that trap running after every Bash command might be too much of a risk.
