### ISSUE TITLE
Ignore line endings when reading .ruby-version.

### ISSUE THREAD

**Issue by pnelson** [postmodern/chruby#311]
I ran into an issue where auto switching was working everywhere except in and old project. Eventually I realized that the .ruby-version file was saved with Windows line endings a long time ago. I saved the file with Unix line endings and then everything worked as expected. Kind of related to #222.

**Comment by postmodern** [comment]
In 9a7f61a27b753021dc0b995ff69b08c4e075b739 I added a string substitution to remove tailing `[[:space:]]`.

**Comment by postmodern** [comment]
@pnelson ping, did chruby HEAD fix the issue?

**Comment by pnelson** [comment]
My apologies for the delay. This fixed my issue. Thanks a lot.
