### ISSUE TITLE
When to formally drop support for MRI 1.8?

### ISSUE THREAD

**Issue by postmodern** [postmodern/chruby#330]
Currently, chruby checks for whether `RUBY_ENGINE` is defined. This code is only needed by MRI 1.8, which is no longer supported or maintained by ruby-core. When should we formally drop support for MRI 1.8? Considering how MRI 1.8 no longer receives security fixes and can't even compile on modern systems, continuing to support it seems harmful to the Ruby ecosystem.

**Comment by aprescott** [comment]
Are there available statistics on MRI versions installed across standard OS images?

**Comment by postmodern** [comment]
Ping @zzak, does ruby-core keep download stats?

**Comment by deivid-rodriguez** [comment]
Less than 1% of the people who filled [this](http://www.askr.me/ruby) in is using it. It'd be useful to know how many people filled it in.

**Comment by postmodern** [comment]
Going to close this as 1.8 is but a memory now.
