### ISSUE TITLE
After upgrade from chruby-0.3.8 to chruby-0.3.9, chruby is not finding any installed rubies.

### ISSUE THREAD

**Issue by tllucero** [postmodern/chruby#350]
markov@wdc05:~/Downloads/chruby-0.3.9$ ./scripts/bug_report.sh
chruby: unknown Ruby: 2.2.3

## System

    Linux wdc05 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu) [/bin/bash]
    chruby version 0.3.9 [/usr/local/bin/chruby-exec]

## Environment

    CHRUBY_VERSION=0.3.9
    SHELL=/bin/bash
    PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/games:/usr/local/games
    HOME=/home/markov
    RUBIES=()
    RUBY_ROOT=
    RUBY_VERSION=
    RUBY_ENGINE=
    RUBY_AUTO_VERSION=
    RUBYLIB=
    RUBYOPT=
    RUBYPATH=
    RUBYSHELL=
    GEM_ROOT=
    GEM_HOME=
    GEM_PATH=

## Hooks

    trap -- '' SIGTSTP
    trap -- '' SIGTTIN
    trap -- '' SIGTTOU
    trap -- '[[ "$BASH_COMMAND" != "$PROMPT_COMMAND" ]] && chruby_auto' DEBUG

## Aliases

    alias 2015='cd /srv/Markets/EodData/Symbols/2015'
    alias __git_find_on_cmdline='__git_find_subcommand'
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'
    alias jazz41='cd /opt/campbell/jazz41.com'
    alias l='ls -CF'
    alias la='ls -A'
    alias ll='ls -alF'
    alias ls='ls --color=auto'
    alias test01='. ~/commands/test01'
    alias tree='. ~/commands/tree.sh'
    alias tth='cd ~/programming/tth'
    alias tth-hc1='cd ~/programming/tth/how-to-website/04-css/01-what-is-css'
    alias tth-hcf='cd ~/programming/tth/how-to-website/05-color-fonts'
    alias tthr3='cd ~/programming/tth/rails/03'

# Installed rubies
ls /usr/local/rubies
2.0.0-p353  2.0.0-p576  2.1.0  2.1.3  2.2.0  2.2.3

# ruby-install version
markov@wdc05:~/Downloads/chruby-0.3.9$ ruby-install -V
ruby-install: 0.5.0

**Comment by postmodern** [comment]
We stopped stopped support `/usr/local/rubies` in 343d99deaab0a1b622d0f530802546635861f196, which was included in the 0.3.0 release. You can manually add those rubies to `RUBIES` in your shell config, or move them to `/opt/rubies/`.
