### ISSUE TITLE
How is "chruby" pronounced?

### ISSUE THREAD

**Issue by To1ne** [postmodern/chruby#352]
Is it like:
- "sh ruby"
- "see haitch ruby"
- "tjruby"
??

**Comment by postmodern** [comment]
I say `C.H. ruby`. The `ch` prefix is a UNIX-ish denoting "change".

**Comment by havenwood** [comment]
And here I say `chuhrooby` but then again I say `chuhroot`.

**Comment by To1ne** [comment]
I know its origin, that's why I am asking. But for example, I pronounce `chmod` as "C.H. mod" and `chown` as "shown".

**Comment by postmodern** [comment]
Going to close this as everyone has their own pronunciation.
