### ISSUE TITLE
Default Ruby in ~/.zprofile: command not found

### ISSUE THREAD

**Issue by nicolaguidi** [postmodern/chruby#354]
I'm following the guide to set a specific Ruby version as default.
Following the instructions if I call the `chruby` command in the `~/.zprofile`  I get this error:
`/Users/Myname/.zprofile:12: command not found: chruby`.

I accomplished my goal calling `chruby` in the `~/.zshrc` file, that makes me think it could be just a wrong instruction.

**Comment by postmodern** [comment]
I refined the wording a bit to mention that first you must load `chruby.sh` in your shell configuration, before adding the "chruby X.Y.Z" line.
