### ISSUE TITLE
How do I install from a git url?

### ISSUE THREAD

**Issue by NullVoxPopuli** [postmodern/chruby#371]
I want to test out the depotimization code: https://github.com/shyouhei/ruby/tree/deoptimization

how do I tell chruby to use this code?

I've tried downloading the code, and compiling, installing, and adding the path to RUBIES, but there was an error re: rubygems.rb.  I'm new to compiling ruby manually, so It's totally possible I messed something up.

**Comment by steakknife** [comment]
Just Install it manually like a regular Ruby to /opt/rubies/deopt-head or something, and open a new shell.

**Comment by postmodern** [comment]
You could also compile it manually:

    ./configure --prefix="$HOME/.rubies/ruby-deoptimized"
    make
    make install
