### ISSUE TITLE
Can't find `ruby-install` rubies on 0.3.9

### ISSUE THREAD

**Issue by coreyti** [postmodern/chruby#376]
Apologies if this is a duplicate; it sounds similar to other open and closed issues, but I don't find a direct match or fix.

Ruby 2.1.2 has been on my system for a while. I just installed 2.3.2 via `ruby-install`, but apparently cannot `chruby` it...

```
user@osx-computer $ ls ~/.rubies/
ruby-2.1.2 ruby-2.3.2

user@osx-computer $ chruby
 * ruby-2.1.2

user@osx-computer $ chruby 2.1.2

user@osx-computer $ chruby 2.3.2
chruby: unknown Ruby: 2.3.2
```

**Comment by postmodern** [comment]
Probably need to restart your shell. Open a new tab or run `exec $SHELL`. An unfortunate design flaw where chruby will only detect available rubies during startup.

**Comment by coreyti** [comment]
Thanks helping out, and apologies for the delay on my side. I don't actually recall if I solved this, or what I did if so, or on what computer that would be. I haven't been having any trouble of late, so all must be fine in the world.

Thanks again.
