### ISSUE TITLE
Chruby 2.4.0 returning a pre-release

### ISSUE THREAD

**Issue by schneems** [postmodern/chruby#387]
First: thanks for chruby, love it.

I ran into a problem over christmas regarding using the release version of 2.4.0 and chruby. I've got all the pre-release versions of 2.4.0 on my machine

```
$ chruby
# ...
   ruby-2.4.0
   ruby-2.4.0-preview1
   ruby-2.4.0-preview2
   ruby-2.4.0-preview3
 * ruby-2.4.0-rc1
   ruby-trunk
   schneems-dev
```

I'm using what I think is the latest chruby

```
$ chruby --version
chruby: 0.3.9
```

When I run

```
$ chruby 2.4.0
```

I get

```
$ ruby -v
ruby 2.4.0rc1 (2016-12-12 trunk 57064) [x86_64-darwin16]
```

If I want the release version I have to be really explicit

```
$ chruby ruby-2.4.0
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

Is `chruby 2.4.0` supposed to give me the released version, or is the correct fix to uninstall all the pre-releases?

**Comment by havenwood** [comment]
At the moment the best thing to do is remove prerelease versions. See #278.

**Comment by schneems** [comment]
Thanks!
