### ISSUE TITLE
Cannot source /usr/local/share/chruby/chruby.sh

### ISSUE THREAD

**Issue by CaptChrisD** [postmodern/chruby#398]
In macOS High Sierra the options passed to `ls` must be lowercase

Please see #397 for fix

**Comment by havenwood** [comment]
I haven't been able to reproduce this issue. The system-provided `ls` appears to have the `-A` flag in High Sierra.
```
-A      List all entries except for . and ...  Always set for the super-user.
```
Could you confirm that `command -v ls` returns `/bin/ls`?

**Comment by CaptChrisD** [comment]
So it turns out I have made a mistake... this machine has an alias to a different ls and didn't notice. It uses exa (color output ls replacement).
