### ISSUE TITLE
URL path for truffle-ruby (version 21.1.0) has wrong sdk on MacOS

### ISSUE THREAD

**Issue by nonnenmacher** [postmodern/chruby#458]
Since GraalVM 21.1.0, the JDK version 8 is no longer supported.

I think the 

`https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java8-darwin-amd64-21.1.0.tar.gz`

should perhaps be updated to

`https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java11-darwin-amd64-21.1.0.tar.gz`

**Comment by eregon** [comment]
Thanks for the report, this should probably be moved to https://github.com/postmodern/ruby-install/issues since it's an issue of `ruby-install`.
A workaround is to use `ruby-build` instead.

**Comment by postmodern** [comment]
@nonnenmacher like @eregon said, please submit an issue to ruby-install or try creating a PR by editing [this line](https://github.com/postmodern/ruby-install/blob/257746199f83794294326383d4a3ac8f37ab9d4a/share/ruby-install/truffleruby-graalvm/functions.sh#L15) which contains the `java8` part.
