### ISSUE TITLE
[Wiki] Incorrect wget path for Ruby install

### ISSUE THREAD

**Issue by Mangara** [postmodern/chruby#499]
## Description

The `wget` path in the [Ruby](https://github.com/postmodern/chruby/wiki/Ruby) installation instructions is incorrect. The path contains version `3.2`, but the tar file is of the `3.3` family, leading to a 404 when trying to access the path.

I suspect the path is supposed to be

```
wget https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.xz
```

**Comment by postmodern** [comment]
Fixed. Thank you!
