### ISSUE TITLE
Newly installed ruby not listed in chruby 

### ISSUE THREAD

**Issue by teohm** [postmodern/chruby#74]
After successfully installed a ruby version using ruby-build, chruby does not update the installed ruby list:

```
$ chruby
   jruby-1.7.2
   ruby-1.8.7-p371
 * ruby-1.9.3-p362

$ ruby-build -v 2.0.0-preview2 ~/.rubies/2.0.0-preview2
...
...
Installed ruby-2.0.0-preview2 to ~/.rubies/2.0.0-preview2

$ chruby
   jruby-1.7.2
   ruby-1.8.7-p371
 * ruby-1.9.3-p362
```

Currently, my workaround is to reopen a new terminal to see the updated list. Does it happen to anyone else here?

**Comment by hedgehog** [comment]
Is this functionality still on the road map?

**Comment by postmodern** [comment]
@hedgehog we'd have to replace `$RUBIES` with `$RUBIES_DIRS` or something similar, so not happening until 1.0.

**Comment by habibalamin** [comment]
This kept annoying me, and I couldn't wait, so I decided to just do it myself. I put this in my `.zshrc` (and I'm sure it can be adapted to other shells, too):

```zsh
chruby-reload () {
  eval "RUBIES=($(
    ruby -rshellwords -e '
      puts STDIN.read
        .split("\n")
        .grep_v(/^$/) # reject blank lines
        .grep_v(/^#/) # reject comments
        .flat_map { |path| Dir[File.expand_path(path)] }
        .map { |path| Shellwords.escape(path) }
        .join " "
    ' < ~/.rubiesrc
  ))"
}

alias chruby='chruby-reload && chruby '
```

and my `.rubiesrc` looks like this:

```
# migrating from rbenv
/usr/local/var/rbenv/versions/*

/usr/local/var/versions/ruby/*
```

**Comment by willxy** [comment]
Just ran into this myself.

Is still a DIY, or has something been implemented for this?
